site_name: Notes
site_url: ""
site_dir: 'site'
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: deep orange
    accent: red

not_in_nav: |
  assets/

exclude_docs: |
  !.javascripts

markdown_extensions:
  - attr_list
  - wikilinks
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - .javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://unpkg.com/htmx.org@2.0.4

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  - replace-excalidraw
  - replace-anchor-links
  - search
